# name: Release

# on:
#   push:
#     tags:
#       - '*'

# jobs:
#   test:
#     strategy:
#       matrix:
#         go-version: [1.17.x]
#         os: [ubuntu-latest]
#     runs-on: ${{ matrix.os }}
#     steps:
#     - name: Install Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: ${{ matrix.go-version }}
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: VersionCheck
#       id: versions
#       run: |
#         ./godelw version
#         ./godelw project-version
#         echo "::set-output name=tag_name::CI-$(./godelw project-version)"
#     - name: Package
#       run: |
#         make clean
#         make package
#     - name: Create Release
#       uses: actions/create-release@v1.1.1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#       with:
#         tag_name: ${{ steps.versions.outputs.tag_name }}
#         release_name: ${{ steps.versions.outputs.tag_name }}
#         prerelease: true
#     - name: Upload Release Asset(s)
#       env:
#         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#       run: |
#         assets=()
#         for asset in ./out/package/*; do
#           assets+=("-a" "$asset")
#         done
#         hub release edit "${assets[@]}" -m "" "${{ steps.versions.outputs.tag_name }}"