name: Release

on:
  release:
    types: [created]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: VersionCheck
      id: versions
      run: |
        ./godelw version
        ./godelw project-version
        echo "::set-output name=tag_name::$(./godelw project-version)"
    - name: Package
      run: |
        make clean
        make package

    - name: Install GitHub CLI
      run: |
          sudo apt update
          sudo apt install gh

    - name: Install hub
      run: brew install hub
            
    - name: Upload Release Asset(s)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        assets=()
        for asset in ./out/package/*; do
          assets+=("-a" "$asset")
        done
        gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
        gh release upload "${{ steps.versions.outputs.tag_name }}" "${assets[@]}"
