name: Release

on:
  release:
    types: [created]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: VersionCheck
      id: versions
      run: |
        ./godelw version
        ./godelw project-version
        echo "::set-output name=tag_name::$(./godelw project-version)"
    - name: Package
      run: |
        make clean
        make package

    - name: Install Homebrew
      run: |
        test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
        test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bashrc

    - name: Install hub
      run: brew install hub
            
    - name: Upload Release Asset(s)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        assets=()
        for asset in ./out/package/*; do
          assets+=("-a" "$asset")
        done
        hub release edit "${assets[@]}" -m "" "${{ steps.versions.outputs.tag_name }}"
